### ISSUE TITLE
Changes Required in Auth API

### ISSUE THREAD

**Issue by rushikesh3299** [Sammed7/Mothers-Dining#12]
**SignUp**
- Please remove confirm password field. Password & confirm password is frontend responsibility.
- In signUp response don't send password either plain or hashed
- For admin role keep one password or any type of auth. If user chooses admin role he has to send that password in request that way everyone wont be able to choose to be admin 

**Login**
- S should be small in login response.
- Right now there is no unique userid or anything returned on login response. Please check that & return unique id if needed to authenticate future api's in userflow such as cart or place order.

**Comment by Vaishnavi-Mhetre** [comment]
All the issues are resolved
